spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: post
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: true

app:
  jwtSecret: qwerty007
